version: "3.0"

services:
  web:
    build: .
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}

    ports:
      - "8000:8000"

    depends_on:
      - db

    networks:
      - app-network

  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_HOST_AUTH_METHOD: trust

    ports:
     - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql/data

    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge